"""Add class models and link events

Revision ID: 4c9636c87239
Revises: 
Create Date: 2026-05-11 12:09:56.422955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c9636c87239'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('class_code', sa.String(length=64), nullable=True),
    sa.Column('teacher_user_id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(length=255), nullable=True),
    sa.Column('default_latitude', sa.Float(), nullable=True),
    sa.Column('default_longitude', sa.Float(), nullable=True),
    sa.Column('default_geofence_radius_meters', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classes_class_code'), 'classes', ['class_code'], unique=True)
    op.create_index(op.f('ix_classes_id'), 'classes', ['id'], unique=False)
    op.create_index(op.f('ix_classes_name'), 'classes', ['name'], unique=False)
    op.create_index(op.f('ix_classes_teacher_user_id'), 'classes', ['teacher_user_id'], unique=False)
    op.create_table('class_invitations',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('invited_email', sa.String(length=255), nullable=True),
    sa.Column('invited_username', sa.String(length=255), nullable=True),
    sa.Column('invited_user_id', sa.Integer(), nullable=True),
    sa.Column('invitation_token', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'DECLINED', 'EXPIRED', 'CANCELLED', name='invitation_status'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('declined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['invited_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_class_invitations_class_id'), 'class_invitations', ['class_id'], unique=False)
    op.create_index(op.f('ix_class_invitations_id'), 'class_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_class_invitations_invitation_token'), 'class_invitations', ['invitation_token'], unique=True)
    op.create_index(op.f('ix_class_invitations_invited_email'), 'class_invitations', ['invited_email'], unique=False)
    op.create_index(op.f('ix_class_invitations_invited_user_id'), 'class_invitations', ['invited_user_id'], unique=False)
    op.create_index(op.f('ix_class_invitations_invited_username'), 'class_invitations', ['invited_username'], unique=False)
    op.create_table('class_memberships',
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('TEACHER', 'STUDENT', 'ASSISTANT', name='membership_role'), nullable=False),
    sa.Column('status', sa.Enum('INVITED', 'ACTIVE', 'REMOVED', 'DECLINED', name='membership_status'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_id', 'user_id', name='uq_class_membership_user')
    )
    op.create_index(op.f('ix_class_memberships_class_id'), 'class_memberships', ['class_id'], unique=False)
    op.create_index(op.f('ix_class_memberships_id'), 'class_memberships', ['id'], unique=False)
    op.create_index(op.f('ix_class_memberships_user_id'), 'class_memberships', ['user_id'], unique=False)
    op.add_column('events', sa.Column('class_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_events_class_id'), 'events', ['class_id'], unique=False)
    op.create_foreign_key(None, 'events', 'classes', ['class_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'username')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_index(op.f('ix_events_class_id'), table_name='events')
    op.drop_column('events', 'class_id')
    op.drop_index(op.f('ix_class_memberships_user_id'), table_name='class_memberships')
    op.drop_index(op.f('ix_class_memberships_id'), table_name='class_memberships')
    op.drop_index(op.f('ix_class_memberships_class_id'), table_name='class_memberships')
    op.drop_table('class_memberships')
    op.drop_index(op.f('ix_class_invitations_invited_username'), table_name='class_invitations')
    op.drop_index(op.f('ix_class_invitations_invited_user_id'), table_name='class_invitations')
    op.drop_index(op.f('ix_class_invitations_invited_email'), table_name='class_invitations')
    op.drop_index(op.f('ix_class_invitations_invitation_token'), table_name='class_invitations')
    op.drop_index(op.f('ix_class_invitations_id'), table_name='class_invitations')
    op.drop_index(op.f('ix_class_invitations_class_id'), table_name='class_invitations')
    op.drop_table('class_invitations')
    op.drop_index(op.f('ix_classes_teacher_user_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_name'), table_name='classes')
    op.drop_index(op.f('ix_classes_id'), table_name='classes')
    op.drop_index(op.f('ix_classes_class_code'), table_name='classes')
    op.drop_table('classes')
    # ### end Alembic commands ###
