"""add_class_invitation_notification_type

Revision ID: b45e26af6d5e
Revises: 4c9636c87239
Create Date: 2026-05-11 16:06:11.473985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b45e26af6d5e'
down_revision: Union[str, None] = '4c9636c87239'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
